### ISSUE TITLE
HTTP/1.1: not found

### ISSUE THREAD

**Issue by chrisgaeth** [zeidlos/hamclock-docker#1]
I grabbed the reop and used the docker-compose process. It pulled the info down and started but all I get is the above notice when I try to go to the page. Unfortunately, and docker logs on the container does not report anything back. I am on a Mac with Apple silicon.

**Comment by zeidlos** [comment]
I confirmed it working on apple silicon (M2 in my case) just fine. However, I provided the wrong link to localhost in the readme. Fixed that in https://github.com/zeidlos/hamclock-docker/commit/f651d3e7ef142cdc1194b233373eaa8b17fe3347

Sorry for the inconvenience.
