### ISSUE TITLE
Issues related to updateVersion

### ISSUE THREAD

**Issue by plleg** [zeidlos/hamclock-docker#3]
What is updateVersion ?

What is the purpose of (run.sh):  curl localhost:8080 updateVersion

Even if I remove that line, the container still stops. Details shows two related lines:
- curl: (7) Failed to connect to localhost port 8080 after 0 ms: Couldn't connect to server
- curl: (6) Could not resolve host: updateVersion

**Comment by tgreaves** [comment]
I am having similar issues related to this ticket.

This is what I see in the logs (via docker logs):

>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to localhost port 8080 after 4 ms: Couldn't connect to server
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: updateVersion

**Comment by zeidlos** [comment]
That should make sure that Hamclock is up to date if youre not rebuilding the container image every time.
However, since this didnt work for me either, I've removed it for the time being.

**Comment by ChrisRomp** [comment]
It probably didn't work because the API isn't active while HamClock is prompting for setup.

**Comment by zeidlos** [comment]
> It probably didn't work because the API isn't active while HamClock is prompting for setup.

That's a very good reason.
