### ISSUE TITLE
A fix for lots of issues I found while trying to run this 

### ISSUE THREAD

**Issue by Dkane00** [zeidlos/hamclock-docker#4]
I found many issues while trying to get this going on my linux server.  I have created a branch with all the fixes and have tested the fixes and all is working.  I tried to push the fixes as a separate branch for a pull request but was unable.  Got a Permission denied error when trying to push the branch.  Could be that I don''t know how to properly push for the pull request as I am a little new to using git but I have all the changes and fixes saved in a separate branch ready to push out if you would like them.

**Comment by Dkane00** [comment]
Figured out how to get that pull request up so it is there for you to check out and merge if you want.

**Comment by Szymok** [comment]
The correct docker image is ggilman/hamclock i suppose
